FROM golang:1.5
RUN apt-get update && apt-get install -y iptables kmod   
COPY . /go/src/github.com/docker/libnetwork
COPY cmd/dnet/libnetwork.toml /etc/default/libnetwork.toml
WORKDIR /go/src/github.com/docker/libnetwork
RUN go get github.com/tools/godep
RUN godep go build ./cmd/dnet
ENTRYPOINT ["./dnet"]
